name: dev

include:
  # - compose_server.yaml
  - compose_gitlab.yaml

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - type: bind
        source: ../test/mysql
        target: /var/lib/mysql
    #   - type: bind
    #     source: ./mysql.cnf
    #     target: /etc/mysql/conf.d/my.cnf
    # command: sh -c "chmod 644 /etc/mysql/conf.d/my.cnf && /entrypoint.sh mysqld"

  redis:
    image: redis:7.4.0
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - type: bind
        source: ../test/redis
        target: /data
    command: redis-server --requirepass ${REDIS_PASSWORD}
