name: dev

include:
  # - compose_server.yaml

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - type: bind
        source: ../test/mysql
        target: /var/lib/mysql
    #   - type: bind
    #     source: ./mysql.cnf
    #     target: /etc/mysql/conf.d/my.cnf
    # command: sh -c "chmod 644 /etc/mysql/conf.d/my.cnf && /entrypoint.sh mysqld"

  redis:
    image: redis:7.4.0
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - type: bind
        source: ../test/redis
        target: /data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  gitea:
    image: gitea/gitea:1.21
    ports:
      # Web 访问端口
      - "${GITEA_PORT}:3000"
      # SSH 端口（用于 git clone）
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - type: bind
        source: ../test/gitea-data
        target: /data
    environment:
      - TZ=Asia/Shanghai
