name: git

services:
  gitea:
    image: gitea/gitea:1.21
    ports:
      # Web 访问端口
      - "${GITEA_PORT}:3000"
      # SSH 端口（用于 git clone）
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TZ=Asia/Shanghai
