services:
  s1:
    image: s1:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: s1
    hostname: l
    command: sh -c 'trap "exit" TERM; while true; do sleep 1; done'