services:
  s1:
    image: s1:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: s1
    hostname: l
    command: sh -c 'trap "exit" TERM; while true; do sleep 1; done'
    volumes:
      - ../:/app/code
      - ///var/run/docker.sock:/var/run/docker.sock
