name: dev

services:
  s1:
    image: s1:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: s1
    hostname: l
    command: ["/app/tools-config/docker/run.sh"]
    volumes:
      - ../:/app/tools-config
      - ///var/run/docker.sock:/var/run/docker.sock
      - ./.zsh_history:/root/.zsh_history
      - ./.z:/root/.z
