name: dev

services:
  s1:
    image: s1:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: s1
    hostname: l
    restart: always
    command: sh -c 'trap "exit" TERM; while true; do sleep 1; done'
    ports:
      - "55555:55555" # 开一个端口测试用
    volumes:
      - ../:/app/tools-config
      - ///var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "4406:3306"

  redis:
    image: redis:7.4.0
    restart: always
    ports:
      - "63379:6379"
    command: redis-server --requirepass "123456"
