line-length = 120  # 代码最大行宽
select = [         # 选择的规则
    "F",
    "E",
    "W",
    "UP",
]
ignore = ["F401", "UP015"]  # 忽略的规则

[format]
docstring-code-format = true

[lint.flake8-import-conventions.aliases]
ErrorCode = "err"

[lint.isort]
combine-as-imports = true
lines-after-imports = 2
